[build]
  functions = "backend"
  publish = "dist"  # Ensure this matches the output directory of your frontend build

[dev]
  functions = "backend"
  publish = "dist"  # Ensure this matches the output directory of your frontend build
  command = "node backend/index.js" # Ensure this command starts your backend server
  targetPort = 5000
  port = 8888