name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy codebase to EC2 (including backend)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "."
          target: "/home/ubuntu/app-temp"

      - name: SSH Deploy Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            rm -rf /home/ubuntu/app
            mv /home/ubuntu/app-temp /home/ubuntu/app

            echo "${{ secrets.ENV_VARS }}" | sed 's/\\n/\n/g' > /home/ubuntu/app/.env

            source ~/.nvm/nvm.sh
            nvm use 22

            npm install -g pm2

            cd /home/ubuntu/app/backend || exit 1
            npm install

            pm2 delete mafam-backend || true
            pm2 start index.js --name mafam-backend
            pm2 save