name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install and build
        run: |
          npm ci --prefix backend --omit=dev
          npm ci
          npm run build
          npm audit fix || true

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Restart Services
        run: |
          VPS_USER="${{ secrets.EC2_USER }}"
          VPS_HOST="${{ secrets.EC2_HOST }}"
          APP_DIR="~/app"

          # Step 1: Ensure the app directory on the VPS is owned by the SSH user (ubuntu)
          # This is critical for rsync to have write permissions.
          ssh "${VPS_USER}@${VPS_HOST}" "sudo chown -R ${VPS_USER}:${VPS_USER} ${APP_DIR}"

          # Step 2: Use rsync to transfer files with --delete to synchronize
          # The --chmod flags are useful for new files, but the chown above is paramount.
          rsync -avz --no-times --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r \
            --delete \
            --exclude node_modules \
            --exclude .git \
            --exclude .env \
            . "${VPS_USER}@${VPS_HOST}:${APP_DIR}/"

          # Step 3: Execute commands on the VPS after files are transferred
          ssh "${VPS_USER}@${VPS_HOST}" << 'EOF'
            set -e # Exit immediately if a command exits with a non-zero status

            cd ~/app

            # Fix permissions for Nginx and runtime after rsync has completed
            sudo chown -R www-data:www-data . # Change ownership to www-data for Nginx
            sudo chmod -R 755 .                # Set directories to 755, files to 755 (all can execute)
            find . -type f -exec sudo chmod 644 {} \; # Correct files back to 644 (only owner can execute)
            
            # Ensure /home/ubuntu/ is traversable by www-data
            sudo chmod o+rx /home/ubuntu/

            # Create/Update .env file for the backend
            printf '%s\n' "${{ secrets.ENV_VARS }}" > .env
            chmod 600 .env # Secure permissions for .env

            # Rebuild dependencies on the server (good practice, but might be redundant if rsync copies node_modules, which it doesn't)
            # This is specifically for backend production dependencies.
            npm ci --prefix backend --omit=dev

            # PM2 management
            pm2 restart mafam-backend --update-env || pm2 start backend/index.js --name mafam-backend --time
            pm2 save # Save PM2 process list to restore on reboot
            
            # Nginx refresh
            sudo systemctl restart nginx
          EOF
