name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install and build
        run: |
          npm ci --prefix backend --omit=dev
          npm ci
          npm run build
          npm audit fix || true

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Restart Services
        run: |
          # Use rsync with proper permissions
          rsync -avz --no-times --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r \
            --delete \
            --exclude node_modules \
            --exclude .git \
            --exclude .env \
            . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app/

          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/app
            
            # Fix permissions
            sudo chown -R $USER:$USER .
            sudo chmod -R 755 .
            find . -type f -exec sudo chmod 644 {} \;
            
            # Create .env
            printf '%s\n' "${{ secrets.ENV_VARS }}" > .env
            chmod 600 .env

            # Rebuild dependencies
            npm ci --prefix backend --omit=dev

            # PM2 management
            pm2 restart mafam-backend --update-env || pm2 start backend/index.js --name mafam-backend --time
            
            # Nginx refresh
            sudo systemctl restart nginx
          EOF
