name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install backend dependencies and build frontend (on runner)
        run: |
          npm install --prefix backend --production # Install production deps for backend
          npm install --production # Install production deps for frontend (assuming root)
          npm run build # Build the frontend (assuming package.json at root)

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Restart Services on VPS
        run: |
          # Copy files to VPS (excluding node_modules, git, and existing .env)
          # We're assuming your app lives in '~/app' on your VPS
          rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env' . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app/

          # Execute commands on the VPS
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app # Navigate to your application directory

            # Create/Update .env file on the server from GitHub Secret
            # Assumes secrets.ENV_VARS has KEY=VALUE pairs separated by NEWLINES
            echo "${{ secrets.ENV_VARS }}" > .env

            # Restart backend using PM2
            # 'mafam-backend' is the assumed name for your PM2 process
            pm2 stop mafam-backend || true
            pm2 delete mafam-backend || true
            pm2 start backend/index.js --name mafam-backend --time
            pm2 save

            # Restart Nginx to serve new frontend files
            sudo systemctl restart nginx
          EOF
