name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy backend folder to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "backend/"
          target: "/home/ubuntu/app/backend-temp"

      - name: SSH Deploy Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            rm -rf /home/ubuntu/app/backend
            mv /home/ubuntu/app/backend-temp /home/ubuntu/app/backend
            cd /home/ubuntu/app/backend

            echo "${{ secrets.ENV_VARS }}" > .env

            source ~/.nvm/nvm.sh
            nvm use 22

            npm install -g pm2

            npm install

            pm2 delete mafam-backend || true
            pm2 start index.js --name mafam-backend
            pm2 save
